# Generated by Django 5.1.5 on 2025-01-29 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('breed', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age_group', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('CALF', 'Calf'), ('HEIFER', 'Heifer'), ('COW', 'Cow'), ('BULL', 'Bull')], default='CALF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
